### ISSUE TITLE
Icon doesn't go away on harvest of Seaweed or Flowers

### ISSUE THREAD

**Issue by AbusiveTuna** [AbusiveTuna/DidICompost#1]

**Comment by mxiia** [comment]
Also applies to Belladona/Mushroom patch.

**Comment by mxiia** [comment]
![image](https://user-images.githubusercontent.com/5335202/221788602-af483212-708f-404c-9c9c-126f07a12415.png)
There is no message when you harvest

**Comment by AbusiveTuna** [comment]
> ![image](https://user-images.githubusercontent.com/5335202/221788710-cd0d1af6-9c4e-4d11-8593-0aac83255148.png) There is no message when you harvest

RIP. Unlikely I'll look into a solution for this then. Maybe taking the compost icon away when a seed is planted?

**Comment by AbusiveTuna** [comment]
Fixed in saveState branch
