### ISSUE TITLE
Inverse current behavior

### ISSUE THREAD

**Issue by ffalor** [AbusiveTuna/DidICompost#3]
I think it would be nice to give an option to inverse the current behavior.

Instead of showing the bucket after composting show the bucket if the patch hasn't been composted yet.

**Comment by Xylot** [comment]
I'd love this as well! Maybe something like one of these? 

![Bottomless_compost_bucket-overlay](https://user-images.githubusercontent.com/14049503/224377311-7ba92b0b-4ad0-4bea-a732-2672e292f409.png)
![Bottomless_compost_bucket-overlay (1)](https://user-images.githubusercontent.com/14049503/224377313-fab232d1-73c7-438c-bf3a-25f8e511eee7.png)

**Comment by AbusiveTuna** [comment]
Still considering this change as an option because I think it would work really well and be easy to implement. 
Will probably add this as an option after I work on getting the patch status saved even after the runelite client closes
