### ISSUE TITLE
Feature Request - Remove icon on fully grown patches

### ISSUE THREAD

**Issue by Xylot** [AbusiveTuna/DidICompost#4]
It would be great to have the option to hide the icon on fully grown patches. This would help avoid clutter in dense areas like the Farming Guild, herb patches, etc...

**Comment by AbusiveTuna** [comment]
Adding functionality to track all patches, growth time, etc, might be a bit more than I'm willing to do for this plugin. However, what would you think about the icons going away after x amount of time or when you leave the area?

Example: Icons disappear after 5 minutes 
Example: Icons in farming guild disappear when you leave the farming guild entirely

**Comment by Xylot** [comment]
Can the RuneLite managed patch statuses be used to avoid writing it manually? RuneLite already keeps track of all patches and their respective compost status so it may be easier to display the icon when RuneLite shows it has compost. What do you think?
