### ISSUE TITLE
Limpwurt harvesting leaves icon

### ISSUE THREAD

**Issue by AustinSumigray** [AbusiveTuna/DidICompost#5]
After I harvest a limpwurt patch which I have composted for more yield, the composted icon remains.

**Comment by AbusiveTuna** [comment]
Currently I don't have a work around for this. They don't have a harvest message. Current idea to "fix" it would be to delete the icon a few minutes after the patch has a seed used on it.

**Comment by AbusiveTuna** [comment]
Limps/flowers have no harvest message. Currently no plans to find a work around
